routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ScoutController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome')->name('login');
});
Route::get('/test', 'ManagerController@test');

Route::group(['prefix'=>'panel','as'=>'panel.'], function(){
    Route::get('login', "ManagerController@login");
    Route::post('login', "ManagerController@dologin");
    // Route::get('test', "ManagerController@testAccount");

});

Route::group(['prefix' => 'panel', 'as' => 'panel.', 'middleware' => 'auth'], function(){
    Route::get('dashboard',"ManagerController@dashboard")->name('dashboard');
    Route::get('scout/account', "ManagerController@scout")->name('scout.account');
    Route::post('scout/add/account', "ManagerController@addScout")->name('scout.add.account');
    Route::get('scout/account/local', "ManagerController@localClown")->name('scout.account.local');
    Route::post('scout/account/local', "ManagerController@addLocalClown")->name('scout.add.account.local');
    Route::get('scout/refresh/token/', "ManagerController@refreshToken")->name('refresh.token');
    Route::get('scout/refresh/token/{token}', "ManagerController@refreshToken")->name('refresh.token.update');
    Route::get('scout/delete/token', 'ManagerController@deleteAccount')->name('delete.token');
    Route::get('scout/delete/token/{token}', 'ManagerController@deleteAccount')->name('delete.token.action');
    Route::get('scout/delete/local/', 'ManagerController@deleteLocalAccount')->name('delete.local');
    Route::get('scout/delete/local/{local_id}', 'ManagerController@deleteLocalAccount')->name('delete.local.action');
});

resources/views/dashboard.blade.php
@extends('layout')
@section('title', 'Dashboard')
@section('subtitle', 'Control Panel')
@section('content')


@yield('body')


         
   
@endsection

resources/views/layout.blade.php
<!doctype html>
<html lang="en">

<head>
  <title>@yield('title')</title>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <!--     Fonts and icons     -->
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
  <!-- Material Kit CSS -->
  <link href="{{url('/')}}/assets/css/material-dashboard.css?v=2.1.2" rel="stylesheet" />
  <script src="{{url('/')}}/assets/js/jquery.min.js"></script>
  <script src="{{url('/')}}/assets/js/core/popper.min.js"></script>
  <script src="{{url('/')}}/assets/js/core/bootstrap-material-design.min.js"></script>
</head>
<body>
    <div class="wrapper ">
        <div class="sidebar" data-color="purple" data-background-color="white">
            <div class="logo">
                <a href="https://clownscout.com" class="simple-text logo-normal">
                CLOWNSCOUT
                </a>
            </div>


            <!-- menu bar -->
            <div class="sidebar-wrapper">
                <ul class="nav">
                @include('menu')
                <!-- your sidebar here -->
                </ul>
            </div>


        </div>


        <div class="main-panel">
            <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
                <div class="container-fluid">
                    <div class="navbar-wrapper">
                        <a class="navbar-brand" href="javascript:;">@yield('subtitle')</a>
                    </div>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="navbar-toggler-icon icon-bar"></span>
                        <span class="navbar-toggler-icon icon-bar"></span>
                        <span class="navbar-toggler-icon icon-bar"></span>
                    </button>
                </div>
            </nav>
            <!--end of nav bar -->


            <div class="content">
                <div class="container-fluid">
                    @yield('content')
                </div>
            </div>
            <!--content end -->
        </div>
    </div>
</body>
</html>

resources/views/localaccount.blade.php
@extends('dashboard')
@section('title', 'JS Accounts')
@section('cardtitle', 'Local Accounts')
@section('cardsubtitle', 'The accounts which are to be distributed among the customers ')
@section('body')

<div class="row">
    <div class="col-md-7">
        <div class="card">
            <div class="card-header card-header-primary">
                <h4 class="card-title ">@yield('cardtitle')</h4>
                <p class="card-category">@yield('cardsubtitle')</p>
            </div>
            <div class="card-body">
                @php ($i = 1)
                <div class="col-md-12">
                    <table class="table">
                    <thead>
                        <th>#</th>
                        <th>Local Email</th>
                        <th>JS Account</th>
                        <th>Action</th>
                    </thead>
                        @foreach($localaccount as $js)
                        <tr>
                            <td>{{$i++}}</td>
                            <td>{{$js->email}}</td>
                            <td>{{$js->js->email}}</td>
                            <td class="td-actions text-right">
                                                      
                                <button type="button" rel="tooltip" title="Remove" class="btn btn-danger btn-link btn-sm">
                                    <a class="tokendelete" href="{{route('panel.delete.local')}}/{{$js->id}}">
                                        <i class="material-icons">close</i>
                                    </a>
                                </button>
                        </td>
                        </tr>
                        @endforeach

                    </table>
                </div>
            </div>


        </div>



    </div>



    <div class="col-md-5"> 
    <div class="card">
        <div class="card-header card-header-primary">
            <h4 class="card-title ">Add Local Accounts</h4>
            <p class="card-category">Select parent JS account from drop down and then add local account details</p>
        </div>

        <div class="card-body">
            <form action="{{route('panel.scout.add.account.local')}}" method="POST" >
            <label class="bmd-label-floating">JS Account DropDown</label>
                <select class="form-control" name="js_id">
                    @foreach($jsaccounts as $js)
                        <option value="{{$js->id}}">{{$js->email}}</option>
                    @endforeach
                </select>
                <label class="bmd-label-floating">Local Account Email</label>
                <input type="email" name="email" class="form-control">
                <label class="bmd-label-floating">JS Account Password</label>
                <input type="password" name="password" class="form-control">
                {{csrf_field()}}
                <input type="submit" class="btn btn-primary" value="Add Local Account">
            </form>

        </div>

    </div>
    </div>
</div>
</div>
<script>

$('.tokendelete').on('click', function(e){
    var c = confirm("Do you really want to delete this local account?");
    if(!c) {
        e.preventDefault();
    }
    // alert('ok');
});

</script>

@endsection

resources/views/login.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="author" content="Kodinger">
	<meta name="viewport" content="width=device-width,initial-scale=1">
	<title>My Login Page</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{{ url('css/custom.css')}}">
</head>

<body class="my-login-page">
	<section class="h-100">
		<div class="container h-100">
			<div class="row justify-content-md-center h-100">
				<div class="card-wrapper">
					<div class="brand">
						<img src="{{url('asset/images/logo.jpg')}}" alt="logo">
					</div>
					<div class="card fat">
						<div class="card-body">
						@if ( session('error'))
							<div class="alert alert-danger">
								{{ session('error') }}
							</div>
						@endif
							<h4 class="card-title">Login</h4>
							<form method="POST" class="my-login-validation" action="{{ url('panel/login')}}" novalidate="">
								<div class="form-group">
									<label for="email">E-Mail Address</label>
									<input id="email" type="email" class="form-control" name="email" value="" required autofocus>
									<div class="invalid-feedback">
										Email is invalid
									</div>
								</div>

								<div class="form-group">
									<label for="password">Password
										<a href="#" class="float-right">
											Forgot Password?
										</a>
									</label>
									<input id="password" type="password" class="form-control" name="password" required data-eye>
								    <div class="invalid-feedback">
								    	Password is required
							    	</div>
								</div>

                                {{csrf_field()}}

								<div class="form-group">
									<div class="custom-checkbox custom-control">
										<input type="checkbox" name="remember" id="remember" class="custom-control-input">
										<label for="remember" class="custom-control-label">Remember Me</label>
									</div>
								</div>

								<div class="form-group m-0">
									<button type="submit" class="btn btn-primary btn-block">
										Login
									</button>
								</div>
								
							</form>
						</div>
					</div>
					<div class="footer">
						Copyright &copy; 2021 &mdash; 
					</div>
				</div>
			</div>
		</div>
	</section>

	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
	<script src="js/my-login.js"></script>
</body>
</html>

resources/views/menu.blade.php
<li class="nav-item {{ (route('panel.dashboard') === url()->full()) ? 'active' : ''}}">
    <a class="nav-link" href="{{route('panel.dashboard')}}">
        <i class="material-icons">dashboard</i>
        <p>Dashboard</p>
    </a>
</li>
<li class="nav-item {{ (route('panel.scout.account') === url()->full()) ? 'active' : ''}} "><a class="nav-link" href="{{route('panel.scout.account')}}"><i class="material-icons">dashboard</i><p>Jungle Scout Account</p></a></li>
<li class="nav-item {{ (route('panel.scout.account.local') === url()->full()) ? 'active' : ''}} "><a class="nav-link" href="{{route('panel.scout.account.local')}}"><i class="material-icons">dashboard</i><p>Add Local Accounts</p></a></li>

resources/views/scout-account.blade.php
@extends('dashboard')
@section('title', 'JS Accounts')
@section('cardtitle', 'JS Accounts')
@section('cardsubtitle', 'The accounts which are provided by JungleScout ')
@section('body')

<div class="row">
<div class="col-md-8">
        <div class="card">
        <div class="card-header card-header-primary">
            <h4 class="card-title ">@yield('cardtitle')</h4>
            <p class="card-category">@yield('cardsubtitle')</p>
        </div>
        <div class="card-body">

        <section class="row">
            <div class="col-md-12">
                <table class="table">
                @php ($i = 1)
                <thead>
                    <th>#</th>
                    <th>Email</th>
                    <th>File</th>
                    <th>Status</th>
                    <th>Action</th>
                </thead>
                    @foreach($jsaccounts as $js)
                    <tr>
                        <td>{{$i++}}</td>
                        <td>{{$js->email}}</td>
                        <td>{{$js->file}}</td>
                        <td>{{($js->status) ? "active" : "inactive"}}</td>
                        <td class="td-actions text-right">
                            <button type="button" rel="tooltip" title="Refresh Token" class="btn btn-primary btn-link btn-sm">
                                <a target="_blank" href="{{route('panel.refresh.token')}}/{{$js->id}}">
                                    <i class="material-icons">refresh</i>
                                </a>
                            </button>
                            
                            <button type="button" rel="tooltip" title="Remove" class="btn btn-danger btn-link btn-sm">
                            <a class="tokendelete" href="{{route('panel.delete.token')}}/{{$js->id}}">
                                <i class="material-icons">close</i>
                            </a>
                            </button>
                        </td>
                    
                    </tr>
                    @endforeach

                </table>

            </div>

        </section>
        </div>
        </div>
    </div>
    
    
<div class="col-md-4">
    <div class="card">
        <div class="card-header card-header-primary">
            <h4 class="card-title ">Add JS Account</h4>
            <p class="card-category">Insert Valid Credentails</p>
        </div>
        <div class="card-body">
            <form action="{{route('panel.scout.add.account')}}" method="POST" >
                    <label class="bmd-label-floating">JS Account Email</label>
                    <input type="email" name="email" class="form-control">

                    <label class="bmd-label-floating">Password</label>
                    <input type="password" name="password" class="form-control">
                    {{csrf_field()}}
                    <input type="submit" class="btn btn-primary" value="Add JS Account">
            </form>
        </div>  
    </div>

    <div class="clearfix"></div>

</div>


</div>


<script>

$('.tokendelete').on('click', function(e){
    var c = confirm("If you delete this account, all LOCAL ACCOUNT associated with this account will be deleted. Are you sure you want to continue?");
    if(!c) {
        e.preventDefault();
    }
    // alert('ok');
});

</script>
@endsection